name: Terraform GKE and Helm Deployment

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the workflow
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1


    - name: Initialize Terraform
      run: terraform init
      working-directory: ./Terraform
      env: 
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    #- name: Terraform Format
     # run: terraform fmt -check

    #- name: Run Terraform plan
     # run: terraform plan -out=tfplan
      #working-directory: ./Terraform
      #env: 
       # GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform Destroy
      #if: github.ref == 'refs/head/main' && github.event_name == 'push'
      run: terraform destroy
      working-directory: ./Terraform
      env: 
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
